name: Jekyll Docker

on:
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Jekyll
        run: echo "Jekyll workflow disabled for XOSHNAW MARKET"
