name: Jekyll Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        run: echo "Jekyll workflow is working"
